package.json
src/app.module.ts
src/user/user.controller.ts
src/user/user.service.ts
yarn.lock

[ADD] kakaoLogin

---

package-lock.json
package.json
src/app.module.ts
src/config/database-config.ts
src/entities/event.entity.ts
src/entities/event_winner_post.entity.ts
src/entities/main_categories.entity.ts
src/entities/main_sub_categories.entity.ts
src/entities/naming_categories.entity.ts
src/entities/sub_categories.entity.ts
src/entities/weekly_cody.entity.ts
src/main/dto/create-main.dto.ts
src/main/dto/update-main.dto.ts
src/main/main.controller.spec.ts
src/main/main.controller.ts
src/main/main.module.ts
src/main/main.service.spec.ts
src/main/main.service.ts
yarn.lock

Migration과 Entity를 모두 사용하면서 활용하기 쉽지가 않으므로 하나씩 차근차근 해보는 것이 좋을 것 같습니다.
Entity로 활용해보기를 먼저 해보도록 하겠습니다~

제안 : Migration 사용 전, Entity로 create query builder 사용해보기

---

src/API/event/event.module.ts
src/API/product/dto/filter.dto.ts
src/API/product/product.controller.ts
src/API/product/product.repository.ts
src/API/product/product.service.ts

[ADD]filterAPI color, gender,item

[ADD]filterAPI

---

src/API/product/dto/filter.dto.ts
src/API/product/dto/get-filter.dto.ts
src/API/product/product.controller.ts
src/API/product/product.service.ts

타입과 필터 데이터 정제 과정에 문제가 발생하여 이와 관련된 코드 수정

프로덕트 필터 함수/타입 변경

---

src/API/lookbook/lookbook.controller.ts
src/API/lookbook/lookbook.repository.ts
src/API/lookbook/lookbook.service.ts
src/API/order/order.module.ts
src/API/order/order.service.ts

[ADD] lookbookDetail page

---

src/API/user/user.controller.ts
src/API/user/user.repository.ts
src/API/user/user.service.ts

[FIX] kakaoApi

---

src/API/order/order.service.ts
src/API/product/asss.ts
src/API/product/dto/filter.dto.ts
src/API/product/dto/get-filter.dto.ts
src/API/product/product.controller.ts
src/API/product/product.repository.ts
src/API/product/product.service.ts
src/config/database-config.ts
yarn.lock

[ADD] productList page

---

src/API/calendar/calendar.controller.ts
src/API/calendar/calendar.module.ts
src/API/calendar/calendar.repository.ts
src/API/calendar/calendar.service.ts
src/API/order/order.service.ts
src/app.module.ts
src/entities/launching_calendar.entity.ts

ADD calendarlist or detail page 기능구현

[ADD] calendarlist or detail page 기능구현

---

src/API/product/dto/filter.dto.ts
src/API/product/dto/get-filter.dto.ts
src/API/product/product.controller.ts
src/API/product/product.repository.ts
src/API/product/product.service.ts

[ADD] productList & detail & filter & ordering API 기능 구현 완료

[ADD] productList & detail & filter & ordering API 기능 구현 

---

src/API/order/IOrderInterface.ts
src/API/order/dto/create-order.dto.ts
src/API/order/order.controller.ts
src/API/order/order.repository.ts
src/API/order/order.service.ts
src/all-exceptions/all-exceptions.filter.ts

order table 수정과 validator decoration 기능을 제공하는 class-validator 도입해보기.

Revert "Order api 테이블 수정"

---

src/API/snap/dto/create-snap.dto.ts
src/API/snap/dto/update-snap.dto.ts
src/API/snap/snap.controller.ts
src/API/snap/snap.repository.ts
src/API/snap/snap.service.ts
src/app.module.ts

ADD snapList && snapDetail Page 기능구현

[ADD] snapList && snapDetailPage

---

src/API/cart/cart.controller.ts
src/API/cart/cart.repository.ts
src/API/cart/cart.service.ts
src/API/cart/dto/create-cart.dto.ts
src/API/order/entities/order.entity.ts
src/API/order/order.module.ts
src/app.module.ts
src/middleware/auth/auth.middleware.ts
src/middleware/err/exception.filter.ts 

[ADD] cart CRUD

---

.gitignore
src/API/order/IOrderInterface.ts
src/API/order/order.controller.ts
src/API/order/order.repository.ts
src/API/order/order.service.ts
src/API/user/user.repository.ts
src/all-exceptions/all-exceptions.filter.ts
src/middleware/auth/check-user-info-from-auth.middleware.ts

오더 기능 추가 : 구매 시 필요한 유저 정보, 카트 내 상품 정보 API
테이블 칼럼 변화로 인한 orderApi 수정
오더 오류 수정 : 테이블 칼럼 후, 프로덕트 옵션 아이디 쿼리 오류 수정
마이페이지 오더 상태별 정보 API 추가
오더 API 통신 중 수정사항 반영: history 정보 제공 시 구매 스테이터스별 필터나 날짜별 필터링에 대한 변화.
ORDER API 기능별 엔드포인트는 전체적으로 구현 완료,
전체 기능 머지되는 대로, 엔드포인트 정리, 확인과 함께 전체적인 수정사항(미들웨어 연결 등) 반영하여 수정할 것

order API 기능

---

src/API/product/dto/filter.dto.ts
src/API/product/dto/get-filter.dto.ts
src/API/product/product.controller.ts
src/API/product/product.module.ts
src/API/product/product.repository.ts
src/API/product/product.service.ts
src/app.module.ts
src/middleware/auth/check-user-info-from-auth.middleware.ts

[FIX] productWishlist 

---

src/API/like/dto/create-like.dto.ts
src/API/like/dto/update-like.dto.ts
src/API/like/like.controller.ts
src/API/like/like.repository.ts
src/API/like/like.service.ts

[FIX] likePage

---

src/API/like/like.repository.ts
src/API/product/product.repository.ts
src/API/product/product.service.ts

FIX productList && productDetail && like page

[FIX] productList && productDetail && like page

---

src/API/like/like.controller.ts
src/API/product/product.controller.ts
src/API/product/product.repository.ts
src/app.module.ts

[FIX] product reviewRcommend

---

src/API/product/dto/filter.dto.ts
src/API/product/product.repository.ts
src/API/product/product.service.ts

[FIX] productList

---

src/API/cart/cart.controller.ts
src/API/cart/cart.repository.ts
src/API/cart/dto/create-cart.dto.ts
src/API/like/like.controller.ts
src/API/like/like.repository.ts
src/API/lookbook/lookbook.repository.ts
src/API/product/product.controller.ts
src/API/product/product.repository.ts
src/API/product/product.service.ts

fix productList &&  cartList && likeList

[FIX] productList And cartList And likeList

---

src/API/cart/cart.controller.ts
src/API/cart/cart.repository.ts
src/API/cart/cart.service.ts
src/API/cart/dto/create-cart.dto.ts
src/API/like/like.controller.ts
src/API/like/like.repository.ts
src/API/like/like.service.ts
src/API/product/product.repository.ts

[FIX] cart && like

---

README.md
src/API/calendar/calendar.controller.ts
src/API/calendar/calendar.repository.ts
src/API/calendar/calendar.service.ts
src/API/cart/cart.repository.ts
src/API/cart/cart.service.ts
src/API/cart/dto/create-cart.dto.ts
src/API/like/dto/create-like.dto.ts
src/API/like/dto/update-like.dto.ts
src/API/like/like.controller.ts
src/API/like/like.repository.ts
src/API/like/like.service.ts
src/API/product/product.controller.ts
src/API/product/product.repository.ts
src/API/product/product.service.ts

[FIX] cartPage
